# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osi3/osi_sensorspecific.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from osi3 import osi_common_pb2 as osi3_dot_osi__common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='osi3/osi_sensorspecific.proto',
  package='osi3',
  syntax='proto2',
  serialized_options=b'H\001',
  serialized_pb=b'\n\x1dosi3/osi_sensorspecific.proto\x12\x04osi3\x1a\x15osi3/osi_common.proto\"&\n\x17RadarSpecificObjectData\x12\x0b\n\x03rcs\x18\x01 \x01(\x01\"\x19\n\x17LidarSpecificObjectData\"\x1a\n\x18\x43\x61meraSpecificObjectData\"\xc3\x05\n\x1cUltrasonicSpecificObjectData\x12+\n#maximum_measurement_distance_sensor\x18\x01 \x01(\x01\x12\x13\n\x0bprobability\x18\x02 \x01(\x01\x12T\n\x14trilateration_status\x18\x03 \x01(\x0e\x32\x36.osi3.UltrasonicSpecificObjectData.TrilaterationStatus\x12\x37\n\x05trend\x18\x04 \x01(\x0e\x32(.osi3.UltrasonicSpecificObjectData.Trend\x12?\n\tsignalway\x18\x05 \x03(\x0b\x32,.osi3.UltrasonicSpecificObjectData.Signalway\x1aW\n\tSignalway\x12#\n\tsender_id\x18\x01 \x01(\x0b\x32\x10.osi3.Identifier\x12%\n\x0breceiver_id\x18\x02 \x01(\x0b\x32\x10.osi3.Identifier\"\xa9\x01\n\x13TrilaterationStatus\x12 \n\x1cTRILATERATION_STATUS_UNKNOWN\x10\x00\x12\x1e\n\x1aTRILATERATION_STATUS_OTHER\x10\x01\x12)\n%TRILATERATION_STATUS_NOT_TRILATERATED\x10\x02\x12%\n!TRILATERATION_STATUS_TRILATERATED\x10\x03\"\x8b\x01\n\x05Trend\x12\x11\n\rTREND_UNKNOWN\x10\x00\x12\x0f\n\x0bTREND_OTHER\x10\x01\x12\x1e\n\x1aTREND_CONSTANT_APPROACHING\x10\x02\x12\x12\n\x0eTREND_CONSTANT\x10\x03\x12\x15\n\x11TREND_APPROACHING\x10\x04\x12\x13\n\x0fTREND_DEPARTING\x10\x05\x42\x02H\x01'
  ,
  dependencies=[osi3_dot_osi__common__pb2.DESCRIPTOR,])



_ULTRASONICSPECIFICOBJECTDATA_TRILATERATIONSTATUS = _descriptor.EnumDescriptor(
  name='TrilaterationStatus',
  full_name='osi3.UltrasonicSpecificObjectData.TrilaterationStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TRILATERATION_STATUS_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRILATERATION_STATUS_OTHER', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRILATERATION_STATUS_NOT_TRILATERATED', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRILATERATION_STATUS_TRILATERATED', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=554,
  serialized_end=723,
)
_sym_db.RegisterEnumDescriptor(_ULTRASONICSPECIFICOBJECTDATA_TRILATERATIONSTATUS)

_ULTRASONICSPECIFICOBJECTDATA_TREND = _descriptor.EnumDescriptor(
  name='Trend',
  full_name='osi3.UltrasonicSpecificObjectData.Trend',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TREND_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TREND_OTHER', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TREND_CONSTANT_APPROACHING', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TREND_CONSTANT', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TREND_APPROACHING', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TREND_DEPARTING', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=726,
  serialized_end=865,
)
_sym_db.RegisterEnumDescriptor(_ULTRASONICSPECIFICOBJECTDATA_TREND)


_RADARSPECIFICOBJECTDATA = _descriptor.Descriptor(
  name='RadarSpecificObjectData',
  full_name='osi3.RadarSpecificObjectData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rcs', full_name='osi3.RadarSpecificObjectData.rcs', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=100,
)


_LIDARSPECIFICOBJECTDATA = _descriptor.Descriptor(
  name='LidarSpecificObjectData',
  full_name='osi3.LidarSpecificObjectData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=127,
)


_CAMERASPECIFICOBJECTDATA = _descriptor.Descriptor(
  name='CameraSpecificObjectData',
  full_name='osi3.CameraSpecificObjectData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=155,
)


_ULTRASONICSPECIFICOBJECTDATA_SIGNALWAY = _descriptor.Descriptor(
  name='Signalway',
  full_name='osi3.UltrasonicSpecificObjectData.Signalway',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender_id', full_name='osi3.UltrasonicSpecificObjectData.Signalway.sender_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receiver_id', full_name='osi3.UltrasonicSpecificObjectData.Signalway.receiver_id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=464,
  serialized_end=551,
)

_ULTRASONICSPECIFICOBJECTDATA = _descriptor.Descriptor(
  name='UltrasonicSpecificObjectData',
  full_name='osi3.UltrasonicSpecificObjectData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='maximum_measurement_distance_sensor', full_name='osi3.UltrasonicSpecificObjectData.maximum_measurement_distance_sensor', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='probability', full_name='osi3.UltrasonicSpecificObjectData.probability', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trilateration_status', full_name='osi3.UltrasonicSpecificObjectData.trilateration_status', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trend', full_name='osi3.UltrasonicSpecificObjectData.trend', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signalway', full_name='osi3.UltrasonicSpecificObjectData.signalway', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ULTRASONICSPECIFICOBJECTDATA_SIGNALWAY, ],
  enum_types=[
    _ULTRASONICSPECIFICOBJECTDATA_TRILATERATIONSTATUS,
    _ULTRASONICSPECIFICOBJECTDATA_TREND,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=865,
)

_ULTRASONICSPECIFICOBJECTDATA_SIGNALWAY.fields_by_name['sender_id'].message_type = osi3_dot_osi__common__pb2._IDENTIFIER
_ULTRASONICSPECIFICOBJECTDATA_SIGNALWAY.fields_by_name['receiver_id'].message_type = osi3_dot_osi__common__pb2._IDENTIFIER
_ULTRASONICSPECIFICOBJECTDATA_SIGNALWAY.containing_type = _ULTRASONICSPECIFICOBJECTDATA
_ULTRASONICSPECIFICOBJECTDATA.fields_by_name['trilateration_status'].enum_type = _ULTRASONICSPECIFICOBJECTDATA_TRILATERATIONSTATUS
_ULTRASONICSPECIFICOBJECTDATA.fields_by_name['trend'].enum_type = _ULTRASONICSPECIFICOBJECTDATA_TREND
_ULTRASONICSPECIFICOBJECTDATA.fields_by_name['signalway'].message_type = _ULTRASONICSPECIFICOBJECTDATA_SIGNALWAY
_ULTRASONICSPECIFICOBJECTDATA_TRILATERATIONSTATUS.containing_type = _ULTRASONICSPECIFICOBJECTDATA
_ULTRASONICSPECIFICOBJECTDATA_TREND.containing_type = _ULTRASONICSPECIFICOBJECTDATA
DESCRIPTOR.message_types_by_name['RadarSpecificObjectData'] = _RADARSPECIFICOBJECTDATA
DESCRIPTOR.message_types_by_name['LidarSpecificObjectData'] = _LIDARSPECIFICOBJECTDATA
DESCRIPTOR.message_types_by_name['CameraSpecificObjectData'] = _CAMERASPECIFICOBJECTDATA
DESCRIPTOR.message_types_by_name['UltrasonicSpecificObjectData'] = _ULTRASONICSPECIFICOBJECTDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RadarSpecificObjectData = _reflection.GeneratedProtocolMessageType('RadarSpecificObjectData', (_message.Message,), {
  'DESCRIPTOR' : _RADARSPECIFICOBJECTDATA,
  '__module__' : 'osi3.osi_sensorspecific_pb2'
  # @@protoc_insertion_point(class_scope:osi3.RadarSpecificObjectData)
  })
_sym_db.RegisterMessage(RadarSpecificObjectData)

LidarSpecificObjectData = _reflection.GeneratedProtocolMessageType('LidarSpecificObjectData', (_message.Message,), {
  'DESCRIPTOR' : _LIDARSPECIFICOBJECTDATA,
  '__module__' : 'osi3.osi_sensorspecific_pb2'
  # @@protoc_insertion_point(class_scope:osi3.LidarSpecificObjectData)
  })
_sym_db.RegisterMessage(LidarSpecificObjectData)

CameraSpecificObjectData = _reflection.GeneratedProtocolMessageType('CameraSpecificObjectData', (_message.Message,), {
  'DESCRIPTOR' : _CAMERASPECIFICOBJECTDATA,
  '__module__' : 'osi3.osi_sensorspecific_pb2'
  # @@protoc_insertion_point(class_scope:osi3.CameraSpecificObjectData)
  })
_sym_db.RegisterMessage(CameraSpecificObjectData)

UltrasonicSpecificObjectData = _reflection.GeneratedProtocolMessageType('UltrasonicSpecificObjectData', (_message.Message,), {

  'Signalway' : _reflection.GeneratedProtocolMessageType('Signalway', (_message.Message,), {
    'DESCRIPTOR' : _ULTRASONICSPECIFICOBJECTDATA_SIGNALWAY,
    '__module__' : 'osi3.osi_sensorspecific_pb2'
    # @@protoc_insertion_point(class_scope:osi3.UltrasonicSpecificObjectData.Signalway)
    })
  ,
  'DESCRIPTOR' : _ULTRASONICSPECIFICOBJECTDATA,
  '__module__' : 'osi3.osi_sensorspecific_pb2'
  # @@protoc_insertion_point(class_scope:osi3.UltrasonicSpecificObjectData)
  })
_sym_db.RegisterMessage(UltrasonicSpecificObjectData)
_sym_db.RegisterMessage(UltrasonicSpecificObjectData.Signalway)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
