# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osi3/osi_trafficupdate.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from osi3 import osi_version_pb2 as osi3_dot_osi__version__pb2
from osi3 import osi_common_pb2 as osi3_dot_osi__common__pb2
from osi3 import osi_object_pb2 as osi3_dot_osi__object__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='osi3/osi_trafficupdate.proto',
  package='osi3',
  syntax='proto2',
  serialized_options=b'H\001',
  serialized_pb=b'\n\x1cosi3/osi_trafficupdate.proto\x12\x04osi3\x1a\x16osi3/osi_version.proto\x1a\x15osi3/osi_common.proto\x1a\x15osi3/osi_object.proto\"\x80\x01\n\rTrafficUpdate\x12\'\n\x07version\x18\x01 \x01(\x0b\x32\x16.osi3.InterfaceVersion\x12\"\n\ttimestamp\x18\x02 \x01(\x0b\x32\x0f.osi3.Timestamp\x12\"\n\x06update\x18\x03 \x01(\x0b\x32\x12.osi3.MovingObjectB\x02H\x01'
  ,
  dependencies=[osi3_dot_osi__version__pb2.DESCRIPTOR,osi3_dot_osi__common__pb2.DESCRIPTOR,osi3_dot_osi__object__pb2.DESCRIPTOR,])




_TRAFFICUPDATE = _descriptor.Descriptor(
  name='TrafficUpdate',
  full_name='osi3.TrafficUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='osi3.TrafficUpdate.version', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='osi3.TrafficUpdate.timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='update', full_name='osi3.TrafficUpdate.update', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=237,
)

_TRAFFICUPDATE.fields_by_name['version'].message_type = osi3_dot_osi__version__pb2._INTERFACEVERSION
_TRAFFICUPDATE.fields_by_name['timestamp'].message_type = osi3_dot_osi__common__pb2._TIMESTAMP
_TRAFFICUPDATE.fields_by_name['update'].message_type = osi3_dot_osi__object__pb2._MOVINGOBJECT
DESCRIPTOR.message_types_by_name['TrafficUpdate'] = _TRAFFICUPDATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TrafficUpdate = _reflection.GeneratedProtocolMessageType('TrafficUpdate', (_message.Message,), {
  'DESCRIPTOR' : _TRAFFICUPDATE,
  '__module__' : 'osi3.osi_trafficupdate_pb2'
  # @@protoc_insertion_point(class_scope:osi3.TrafficUpdate)
  })
_sym_db.RegisterMessage(TrafficUpdate)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
