stages:
  - Build Images

carla-scenario-runner:
  stage: Build Images
  trigger:
    include:
      - local: docker/.gitlab-ci.yml
    strategy: depend

carla-scenario-runner-ros:
  stage: Build Images
  trigger:
    include:
      - local: docker-ros/.gitlab-ci.yml
    strategy: depend
