workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"      # run child pipeline if triggered by parent pipeline

variables:
  IMAGE_TARGET:     ${CI_REGISTRY_IMAGE}:latest
  IMAGE_CI:         ${IMAGE_TARGET}_${CI_COMMIT_REF_SLUG}_ci
  IMAGE_LATEST:     ${CI_REGISTRY_IMAGE}:latest
  IMAGE_TARGET_TAG: ${IMAGE_TARGET}-${CI_COMMIT_TAG}
  IMAGE_TAG:        ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
  PUSH_AS_LATEST:   'true'
  # -----
  CI_TOKEN_PASSWORD: $CI_REGISTRY_PASSWORD
  # -----
  UBUNTU_VERSION: 24.04
  ARTIFACTS_URL:  https://gitlab.ika.rwth-aachen.de/api/v4/projects/1645/jobs/artifacts/ue5-ika/download?job=build-client-docker-image
  # -----
  DOCKER_DRIVER:      overlay2
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_BUILDKIT:    1

stages:
  - Build Image
  - Push Image

default:
  image: docker:20.10.22-git
  services:
    - docker:20.10.22-dind
  tags:
    - privileged
    - amd64
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

.build:
  script:
    - |-
      docker build \
        --file docker/Dockerfile \
        --tag "${IMG}" \
        --build-arg "UBUNTU_VERSION=${UBUNTU_VERSION}" \
        --build-arg "ARTIFACTS_URL=${ARTIFACTS_URL}" \
        --build-arg "CI_JOB_TOKEN=${CI_TOKEN_PASSWORD}" \
        .
    - docker push "${IMG}"

run:
  stage: Build Image
  extends: .build
  variables:
    IMG: ${IMAGE_CI}

.push:
  needs:
    - job: run
      optional: true
  script:
    - |-
      if [[ "${IMG}" == "${IMAGE_CI}" ]]; then
        echo "Image ${IMG} was already pushed by the build job."
      else
        docker pull "${IMAGE_CI}"
        docker tag "${IMAGE_CI}" "${IMG}"
        docker push "${IMG}"
      fi

Push CI:
  stage: Push Image
  extends: .push
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
  variables:
    IMG: ${IMAGE_CI}

Push:
  stage: Push Image
  extends: .push
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    IMG: ${IMAGE_TARGET}

Push latest:
  stage: Push Image
  extends: .push
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $PUSH_AS_LATEST == 'true'
  variables:
    IMG: ${IMAGE_LATEST}

Push target tag:
  stage: Push Image
  extends: .push
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    IMG: ${IMAGE_TARGET_TAG}

Push tag:
  stage: Push Image
  extends: .push
  rules:
    - if: $CI_COMMIT_TAG && $PUSH_AS_LATEST == 'true'
  variables:
    IMG: ${IMAGE_TAG}
