x-ubuntu-version: &ubuntu-version 24.04
x-artifacts-url:  &artifacts-url  https://gitlab.ika.rwth-aachen.de/api/v4/projects/1645/jobs/artifacts/main/download?job=provide-carla-artifacts
x-image:          &image          gitlab.ika.rwth-aachen.de:5050/fb-fi/simulation/carla/carla-scenario-runner:latest

# ==============================================================================

x-build: &build
  dockerfile: ./docker/Dockerfile
  context: ../
  args:
    UBUNTU_VERSION: *ubuntu-version
    ARTIFACTS_URL: *artifacts-url
    CI_JOB_TOKEN: $CI_TOKEN_PASSWORD
    CI_REPOSITORY_URL: $CI_REPO_URL

services:
  run:
    image: *image
    build:
      <<: *build
