# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ScenarioRunner.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from osi3 import osi_trafficcommand_pb2 as osi3_dot_osi__trafficcommand__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14ScenarioRunner.proto\x12\x12srunner.osi.client\x1a\x1dosi3/osi_trafficcommand.proto\"\x16\n\x05\x46loat\x12\r\n\x05value\x18\x01 \x01(\x02\x32X\n\x14OSIVehicleController\x12@\n\x0bSendCommand\x12\x14.osi3.TrafficCommand\x1a\x19.srunner.osi.client.Float\"\x00\x62\x06proto3')



_FLOAT = DESCRIPTOR.message_types_by_name['Float']
Float = _reflection.GeneratedProtocolMessageType('Float', (_message.Message,), {
  'DESCRIPTOR' : _FLOAT,
  '__module__' : 'ScenarioRunner_pb2'
  # @@protoc_insertion_point(class_scope:srunner.osi.client.Float)
  })
_sym_db.RegisterMessage(Float)

_OSIVEHICLECONTROLLER = DESCRIPTOR.services_by_name['OSIVehicleController']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FLOAT._serialized_start=75
  _FLOAT._serialized_end=97
  _OSIVEHICLECONTROLLER._serialized_start=99
  _OSIVEHICLECONTROLLER._serialized_end=187
# @@protoc_insertion_point(module_scope)
