include:
  - remote: 'https://raw.githubusercontent.com/ika-rwth-aachen/docker-ros/main/.gitlab-ci/docker-ros.yml'

variables:
  BASE_IMAGE: rwthika/ros2:jazzy
  IMAGE_NAME: ${CI_REGISTRY_IMAGE}/ros
  RMW_IMPLEMENTATION: rmw_zenoh_cpp
  COMMAND: ros2 launch carla_ros_scenario_runner carla_ros_scenario_runner.launch.py scenario_runner_path:=$SCENARIO_RUNNER_ROOT
  TARGET: dev,run
  PLATFORM: amd64
  DISABLE_ROS_INSTALLATION: 'true'
  ENABLE_INDUSTRIAL_CI: 'false'
  ENABLE_SLIM: 'false'
  VCS_IMPORT_FILE: docker-ros/carla-scenario-runner-ros.repos
  ADDITIONAL_FILES_DIR: ./
  ADDITIONAL_PIP_FILE: docker-ros/additional-pip-requirements.txt
  AFTER_DEPENDENCY_INSTALLATION_SCRIPT: docker-ros/custom.sh
