name: Docker

on: [push, pull_request]

permissions:
  contents: read
  packages: write

jobs:
  
  clean-up:
    name: Clean up
    runs-on: ubuntu-latest
    steps:
      - name: Clean up
        run: rm -rf *
        
  create-image:
    name: Create docker image
    runs-on: ubuntu-latest
    needs: clean-up
    env: 
      IMAGE_TAG_SUFFIX: ""
    steps:

      - uses: actions/checkout@v4
        name: Checkout repository
        with: 
          path: carla-scenario-runner
          submodules: true
          
      - uses: docker/login-action@v3
        name: Login to GHCR
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: robinraju/release-downloader@v1.8
        name: Download PythonAPI
        with:
          repository: openads-project/carla-simulator
          tag: v0.10.0-1.0.0
          fileName: PythonAPI.tar.gz
          extract: true
          out-file-path: carla-scenario-runner/docker
        
      - name: Set image tag
        run: |
          echo "IMAGE_TAG_SUFFIX=_$(echo '${{ github.ref_name }}' | tr / -)_ci" >> $GITHUB_ENV
        if: github.ref_name != github.event.repository.default_branch
      
      - uses: docker/build-push-action@v5
        name: Build and push
        with:
          push: true
          file: carla-scenario-runner/docker/Dockerfile
          tags: ghcr.io/${{ github.repository }}:latest${{env.IMAGE_TAG_SUFFIX}}
          no-cache: true
          context: carla-scenario-runner
