name: Docker

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
          
  create-image:
    name: Create docker image
    runs-on: ubuntu-latest
    env: 
      IMAGE_TAG_SUFFIX: ""
    steps:

      - uses: actions/checkout@v4
        name: Checkout repository
        with: 
          path: carla-scenario-runner
          submodules: true
          
      - uses: docker/login-action@v3
        name: Login to GHCR
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Set image tag
        run: |
          echo "IMAGE_TAG_SUFFIX=_$(echo '${{ github.ref_name }}' | tr / -)_ci" >> $GITHUB_ENV
        if: github.ref_name != github.event.repository.default_branch
      
      - uses: docker/build-push-action@v5
        name: Build and push
        with:
          push: true
          file: carla-scenario-runner/docker/Dockerfile
          tags: ghcr.io/${{ github.repository }}:latest${{env.IMAGE_TAG_SUFFIX}}
          no-cache: true
          context: carla-scenario-runner
          build-args: |
            ARTIFACTS_URL=https://github.com/openads-project/carla-simulator/releases/download/v0.10.0-1.0.0/PythonAPI.tar.gz
